apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-label # berbeda dari yg di nginx.yaml
  labels: # label key-value, bisa difilter
    team: engineer
    version: 1.4.5
    environment: development
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    